language: python
python:
  - "2.7"
  - "2.6"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libevent-dev
install: pip install -r test-requirements.txt -r requirements.txt --use-mirrors
script: make test

